name = "TallyProofs"
uuid = "d02cb14a-d84c-4a2f-bcbc-d08609c437b3"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[deps]
CryptoGroups = "bc997328-bedd-407e-bcd3-5758e064a52d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ShuffleProofs = "31a120cc-b3cb-4d07-bbdb-d498660ddfd8"

[compat]
CryptoGroups = "0.4.1"
Random = "1.11.0"
ShuffleProofs = "0.3.1"
